library(tidyverse)
library(blsAPI)
library(tidycensus)
library(jsonlite)
library(lubridate)
library(janitor)
library(openxlsx)
library(gt)
library(scales)
library(dplyr)
library(ggalt)
library(tidyr)
library(ggtext)
library(haven)
########################################
### IPUMS CPS DATA
########################################

setwd("C:/Users/hliu/Desktop/Monthly_Economic_Update/Current")
cps_data <- read_sas("cps_00006.sas7bdat")

philly <- cps_data %>%
  filter(STATEFIP == 42, COUNTY == 42101)
philly <- philly %>%
  mutate(
    statefip_recoded = factor(STATEFIP,
                              levels = c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,
                                         24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,
                                         44,45,46,47,48,49,50,51,53,54,55,56,61,65,68,69,70,71,72,
                                         73,74,75,76,77,78,79,80,81,83,84,85,87,88,89,90,99),
                              labels = c("Alabama", "Alaska", "Arizona", "Arkansas", "California",
                                         "Colorado", "Connecticut", "Delaware", "District of Columbia",
                                         "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana",
                                         "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
                                         "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
                                         "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
                                         "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
                                         "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
                                         "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia",
                                         "Washington", "West Virginia", "Wisconsin", "Wyoming",
                                         "Maine-New Hampshire-Vermont", "Montana-Idaho-Wyoming",
                                         "Alaska-Hawaii", "Nebraska-North Dakota-South Dakota",
                                         "Maine-Massachusetts-New Hampshire-Rhode Island-Vermont",
                                         "Michigan-Wisconsin", "Minnesota-Iowa",
                                         "Nebraska-North Dakota-South Dakota-Kansas",
                                         "Delaware-Virginia", "North Carolina-South Carolina",
                                         "Alabama-Mississippi", "Arkansas-Oklahoma",
                                         "Arizona-New Mexico-Colorado", "Idaho-Wyoming-Utah-Montana-Nevada",
                                         "Alaska-Washington-Hawaii", "New Hampshire-Maine-Vermont-Rhode Island",
                                         "South Carolina-Georgia", "Kentucky-Tennessee",
                                         "Arkansas-Louisiana-Oklahoma",
                                         "Iowa-N Dakota-S Dakota-Nebraska-Kansas-Minnesota-Missouri",
                                         "Washington-Oregon-Alaska-Hawaii",
                                         "Montana-Wyoming-Colorado-New Mexico-Utah-Nevada-Arizona",
                                         "Delaware-Maryland-Virginia-West Virginia", "State not identified")
    ),
    
    ## 4. COUNTY: For simplicity, if COUNTY equals 42101 we call it "Philadelphia County"
    county_recoded = if_else(COUNTY == 42101, "Philadelphia County",
                             as.character(COUNTY)),
    race_recoded = case_when(
      RACE == 100 ~ "White",
      RACE == 200 ~ "Black",
      RACE == 300 ~ "American Indian/Alaska Native",
      RACE %in% c(650,651,652) ~ "Asian/Pacific Islander",
      RACE == 700 ~ "Other",
      RACE >= 801 & RACE <= 819 ~ "Mixed race",
      RACE == 820 ~ "Two or three races, unspecified",
      RACE == 830 ~ "Four or five races, unspecified",
      TRUE ~ as.character(RACE)
    ),
    empstat_recoded = recode_factor(as.character(EMPSTAT),
                                    "00" = "NIU",
                                    "01" = "Armed Forces",
                                    "10" = "At work",
                                    "12" = "Has job, not at work last week",
                                    "20" = "Unemployed",
                                    "21" = "Unemployed, experienced",
                                    "22" = "Unemployed, new",
                                    "30" = "Not in labor force",
                                    "31" = "NILF, housework",
                                    "32" = "NILF, unable to work",
                                    "33" = "NILF, school",
                                    "34" = "NILF, other",
                                    "35" = "NILF, unpaid (<15 hrs)",
                                    "36" = "NILF, retired"
    ),
    labforce_recoded = factor(LABFORCE,
                              levels = c(0,1,2),
                              labels = c("NIU", "Not in labor force", "In labor force")
    ),
    classwkr_recoded = recode_factor(as.character(CLASSWKR),
                                     "00" = "NIU",
                                     "10" = "Self-employed",
                                     "13" = "Self-employed, not incorporated",
                                     "14" = "Self-employed, incorporated",
                                     "20" = "Works for wages/salary",
                                     "21" = "Wage/salary, private",
                                     "22" = "Private, for profit",
                                     "23" = "Private, nonprofit",
                                     "24" = "Wage/salary, government",
                                     "25" = "Federal government employee",
                                     "26" = "Armed forces",
                                     "27" = "State government employee",
                                     "28" = "Local government employee",
                                     "29" = "Unpaid family worker",
                                     "99" = "Missing/Unknown"
    ),
    
    ## 12. WHYUNEMP: Reason for unemployment
    whyunemp_recoded = recode_factor(as.character(WHYUNEMP),
                                     "0" = "NIU",
                                     "1" = "Job loser - on layoff",
                                     "2" = "Other job loser",
                                     "3" = "Temporary job ended",
                                     "4" = "Job leaver",
                                     "5" = "Re-entrant",
                                     "6" = "New entrant"
    )
  )

philly <- philly %>% 
  mutate(
    ind_recoded = case_when(
      IND == 0    ~ "N/A (not applicable)",
      IND == 170  ~ "Crop production",
      IND == 180  ~ "Animal production",
      IND == 190  ~ "Forestry except logging",
      IND == 270  ~ "Logging",
      IND == 280  ~ "Fishing, hunting, and trapping",
      IND == 290  ~ "Support activities for agriculture and forestry",
      IND == 370  ~ "Oil and gas extraction",
      IND == 380  ~ "Coal mining",
      IND == 390  ~ "Metal ore mining",
      IND == 470  ~ "Nonmetallic mineral mining and quarrying",
      IND == 490  ~ "Support activities for mining",
      IND == 770  ~ "Construction",
      IND == 1070 ~ "Animal food, grain, and oilseed milling",
      IND == 1080 ~ "Sugar and confectionery products",
      IND == 1090 ~ "Fruit and vegetable preserving and specialty food manufacturing",
      IND == 1170 ~ "Dairy product manufacturing",
      IND == 1180 ~ "Animal slaughtering and processing",
      IND == 1190 ~ "Retail bakeries",
      IND == 1270 ~ "Bakeries and tortilla manufacturing, except retail",
      IND == 1280 ~ "Seafood and other miscellaneous foods, n.e.c.",
      IND == 1290 ~ "Not specified food industries",
      IND == 1370 ~ "Beverage manufacturing",
      IND == 1390 ~ "Tobacco manufacturing",
      IND == 1470 ~ "Fiber, yarn, and thread mills",
      IND == 1480 ~ "Fabric mills, except knitting mills",
      IND == 1490 ~ "Textile and fabric finishing and coating mills",
      IND == 1570 ~ "Carpet and rug mills",
      IND == 1590 ~ "Textile product mills, except carpet and rug",
      IND == 1670 ~ "Knitting mills, and apparel knitting mills",
      IND == 1691 ~ "Cut and sew, and apparel accessories and other apparel manufacturing",
      IND == 1770 ~ "Footwear manufacturing",
      IND == 1790 ~ "Leather tanning and finishing and other leather and allied products manufacturing",
      IND == 1870 ~ "Pulp, paper, and paperboard mills",
      IND == 1880 ~ "Paperboard containers and boxes",
      IND == 1890 ~ "Miscellaneous paper and pulp products",
      IND == 1990 ~ "Printing and related support activities",
      IND == 2070 ~ "Petroleum refining",
      IND == 2090 ~ "Miscellaneous petroleum and coal products",
      IND == 2170 ~ "Resin, synthetic rubber and fibers, and filaments manufacturing",
      IND == 2180 ~ "Agricultural chemical manufacturing",
      IND == 2190 ~ "Pharmaceutical and medicine manufacturing",
      IND == 2270 ~ "Paint, coating, and adhesives manufacturing",
      IND == 2280 ~ "Soap, cleaning compound, and cosmetic manufacturing",
      IND == 2290 ~ "Industrial and miscellaneous chemicals",
      IND == 2370 ~ "Plastics product manufacturing",
      IND == 2380 ~ "Tire manufacturing",
      IND == 2390 ~ "Rubber product, except tire, manufacturing",
      IND == 2470 ~ "Pottery, ceramics, and plumbing fixture manufacturing",
      IND == 2480 ~ "Structural clay product manufacturing",
      IND == 2490 ~ "Glass and glass product manufacturing",
      IND == 2570 ~ "Cement, concrete, lime, and gypsum product manufacturing",
      IND == 2590 ~ "Miscellaneous nonmetallic mineral product manufacturing",
      IND == 2670 ~ "Iron and steel mills and steel product manufacturing",
      IND == 2680 ~ "Aluminum production and processing",
      IND == 2690 ~ "Nonferrous metal (except aluminum) production and processing",
      IND == 2770 ~ "Foundries",
      IND == 2780 ~ "Metal forgings and stampings",
      IND == 2790 ~ "Cutlery and hand tool manufacturing",
      IND == 2870 ~ "Structural metals, and boiler, tank, and shipping container manufacturing",
      IND == 2880 ~ "Machine shops; turned product; screw, nut, and bolt manufacturing",
      IND == 2890 ~ "Coating, engraving, heat treating and allied activities",
      IND == 2970 ~ "Ordnance",
      IND == 2980 ~ "Miscellaneous fabricated metal products manufacturing",
      IND == 2990 ~ "Not specified metal industries",
      IND == 3070 ~ "Agricultural implement manufacturing",
      IND == 3080 ~ "Construction, and mining and oil and gas field machinery manufacturing",
      IND == 3095 ~ "Commercial and service industry machinery manufacturing",
      IND == 3170 ~ "Metalworking machinery manufacturing",
      IND == 3180 ~ "Engines, turbines, and power transmission equipment manufacturing",
      IND == 3291 ~ "Machinery manufacturing, n.e.c. or not specified",
      IND == 3365 ~ "Computer and peripheral equipment manufacturing",
      IND == 3370 ~ "Communications, and audio and video equipment manufacturing",
      IND == 3380 ~ "Navigational, measuring, electromedical, and control instruments manufacturing",
      IND == 3390 ~ "Electronic component and product manufacturing, n.e.c.",
      IND == 3470 ~ "Household appliance manufacturing",
      IND == 3490 ~ "Electrical lighting and electrical equipment manufacturing, and other electrical component manufacturing, n.e.c.",
      IND == 3570 ~ "Motor vehicles and motor vehicle equipment manufacturing",
      IND == 3580 ~ "Aircraft and parts manufacturing",
      IND == 3590 ~ "Aerospace product and parts manufacturing",
      IND == 3670 ~ "Railroad rolling stock manufacturing",
      IND == 3680 ~ "Ship and boat building",
      IND == 3690 ~ "Other transportation equipment manufacturing",
      IND == 3770 ~ "Sawmills and wood preservation",
      IND == 3780 ~ "Veneer, plywood, and engineered wood products",
      IND == 3790 ~ "Prefabricated wood buildings and mobile homes",
      IND == 3875 ~ "Miscellaneous wood products",
      IND == 3895 ~ "Furniture and related product manufacturing",
      IND == 3960 ~ "Medical equipment and supplies manufacturing",
      IND == 3970 ~ "Sporting and athletic goods, and doll, toy and game manufacturing",
      IND == 3980 ~ "Miscellaneous manufacturing, n.e.c.",
      IND == 3990 ~ "Not specified manufacturing industries",
      IND == 4070 ~ "Motor vehicles, parts and supplies, merchant wholesalers",
      IND == 4080 ~ "Furniture and home furnishing, merchant wholesalers",
      IND == 4090 ~ "Lumber and other construction materials, merchant wholesalers",
      IND == 4170 ~ "Professional and commercial equipment and supplies, merchant wholesalers",
      IND == 4180 ~ "Metals and minerals, except petroleum, merchant wholesalers",
      IND == 4195 ~ "Electrical and electronic goods, merchant wholesalers",
      IND == 4265 ~ "Hardware, plumbing and heating equipment, and supplies, merchant wholesalers",
      IND == 4270 ~ "Machinery, equipment, and supplies, merchant wholesalers",
      IND == 4280 ~ "Recyclable material, merchant wholesalers",
      IND == 4290 ~ "Miscellaneous durable goods, except recyclable material, merchant wholesalers",
      IND == 4370 ~ "Paper and paper products, merchant wholesalers",
      IND == 4380 ~ "Drugs, sundries, and chemical and allied products, merchant wholesalers",
      IND == 4390 ~ "Apparel, piece goods, and notions, merchant wholesalers",
      IND == 4470 ~ "Groceries and related products, merchant wholesalers",
      IND == 4480 ~ "Farm product raw materials, merchant wholesalers",
      IND == 4490 ~ "Petroleum and petroleum products, merchant wholesalers",
      IND == 4560 ~ "Alcoholic beverages, merchant wholesalers",
      IND == 4570 ~ "Farm supplies, merchant wholesalers",
      IND == 4580 ~ "Miscellaneous nondurable goods, except farm supplies, wholesalers",
      IND == 4585 ~ "Wholesale electronics markets, agents and brokers",
      IND == 4590 ~ "Not specified wholesale trade",
      IND == 4670 ~ "Automobile dealers",
      IND == 4680 ~ "Other motor vehicle dealers",
      IND == 4690 ~ "Auto parts, accessories, and tire stores",
      IND == 4770 ~ "Furniture and home furnishings stores",
      IND == 4780 ~ "Household appliance stores",
      IND == 4795 ~ "Electronics stores",
      IND == 4870 ~ "Building material and supplies dealers",
      IND == 4880 ~ "Hardware stores",
      IND == 4890 ~ "Lawn and garden equipment and supplies stores",
      IND == 4971 ~ "Supermarkets and other grocery (except convenience) stores",
      IND == 4972 ~ "Convenience Stores",
      IND == 4981 ~ "Specialty food retailers",
      IND == 4990 ~ "Beer, wine, and liquor stores",
      IND == 5070 ~ "Pharmacies and drug stores",
      IND == 5080 ~ "Health and personal care, except drug, stores",
      IND == 5090 ~ "Gasoline stations",
      IND == 5170 ~ "Clothing stores",
      IND == 5171 ~ "Clothing and clothing accessories retailers",
      IND == 5180 ~ "Shoe stores",
      IND == 5190 ~ "Jewelry, luggage, and leather goods stores",
      IND == 5275 ~ "Sporting goods, camera, and hobby and toy stores",
      IND == 5280 ~ "Sewing, needlework and piece goods stores",
      IND == 5295 ~ "Musical instrument and supplies stores",
      IND == 5370 ~ "Book stores and news dealers",
      IND == 5381 ~ "Department stores",  # if applicable from earlier
      IND == 5382 ~ "Department stores",
      IND == 5391 ~ "General merchandise stores, including warehouse clubs and supercenters",
      IND == 5392 ~ "Warehouse clubs, supercenters, and other general merchandise retailers",
      IND == 5471 ~ "Florists",
      IND == 5480 ~ "Office supplies and stationery stores",
      IND == 5490 ~ "Used merchandise stores",
      IND == 5570 ~ "Gift, novelty, and souvenir shops",
      IND == 5580 ~ "Miscellaneous retail stores",
      IND == 5593 ~ "Electronic shopping and mail-order houses",
      IND == 5670 ~ "Vending machine operators",
      IND == 5680 ~ "Fuel dealers",
      IND == 5690 ~ "Other direct selling establishments",
      IND == 5790 ~ "Not specified retail trade",
      IND == 6070 ~ "Air transportation",
      IND == 6080 ~ "Rail transportation",
      IND == 6090 ~ "Water transportation",
      IND == 6170 ~ "Truck transportation",
      IND == 6180 ~ "Bus service and urban transit",
      IND == 6190 ~ "Taxi and limousine service",
      IND == 6270 ~ "Pipeline transportation",
      IND == 6280 ~ "Scenic and sightseeing transportation",
      IND == 6290 ~ "Services incidental to transportation",
      IND == 6370 ~ "Postal Service",
      IND == 6380 ~ "Couriers and messengers",
      IND == 6390 ~ "Warehousing and storage",
      IND == 570  ~ "Electric power generation, transmission and distribution",
      IND == 580  ~ "Natural gas distribution",
      IND == 590  ~ "Electric and gas, and other combinations",
      IND == 670  ~ "Water supply and irrigation systems, and steam and air-conditioning supply",
      IND == 680  ~ "Sewage treatment facilities",
      IND == 690  ~ "Not specified utilities",
      IND == 6470 ~ "Newspaper publishers",
      IND == 6480 ~ "Periodical, book, and directory publishers",
      IND == 6481 ~ "Periodical, book, and directory and mailing list, and other publishers",
      IND == 6490 ~ "Software publishers",
      IND == 6570 ~ "Motion pictures and video industries",
      IND == 6590 ~ "Sound recording industries",
      IND == 6670 ~ "Broadcasting (except internet)",
      IND == 6672 ~ "Internet publishing and broadcasting and web search portals",
      IND == 6680 ~ "Wired telecommunications carriers",
      IND == 6690 ~ "Telecommunications, except wired telecommunications carriers",
      IND == 6695 ~ "Data processing, hosting, and related services",
      IND == 6770 ~ "Libraries and archives",
      IND == 6780 ~ "Other information services, except libraries and archives, and internet publishing and broadcasting and web search portals",
      IND == 6781 ~ "Web search portals and all other information services",
      IND == 6870 ~ "Banking and related activities",
      IND == 6880 ~ "Savings institutions, including credit unions",
      IND == 6890 ~ "Non-depository credit and related activities",
      IND == 6970 ~ "Securities, commodities, funds, trusts, and other financial investments",
      IND == 6991 ~ "Insurance carriers",
      IND == 6992 ~ "Agencies, brokerages, and other insurance related activities",
      IND == 7071 ~ "Lessors of real estate, and offices of real estate agents and brokers",
      IND == 7072 ~ "Real estate property managers, offices of real estate appraisers, and other activities related to real estate",
      IND == 7080 ~ "Automotive equipment rental and leasing",
      IND == 7181 ~ "Other consumer goods rental",
      IND == 7190 ~ "Commercial, industrial, and other intangible assets rental and leasing",
      IND == 7270 ~ "Legal services",
      IND == 7280 ~ "Accounting, tax preparation, bookkeeping and payroll services",
      IND == 7290 ~ "Architectural, engineering, and related services",
      IND == 7370 ~ "Specialized design services",
      IND == 7380 ~ "Computer systems design and related services",
      IND == 7390 ~ "Management, scientific and technical consulting services",
      IND == 7460 ~ "Scientific research and development services",
      IND == 7470 ~ "Advertising and related services",
      IND == 7480 ~ "Veterinary services",
      IND == 7490 ~ "Other professional, scientific and technical services, except veterinary",
      IND == 7570 ~ "Management of companies and enterprises",
      IND == 7580 ~ "Employment services",
      IND == 7590 ~ "Business support services",
      IND == 7670 ~ "Travel arrangements and reservation services",
      IND == 7680 ~ "Investigation and security services",
      IND == 7690 ~ "Services to buildings and dwellings (except cleaning during construction and immediately after construction)",
      IND == 7770 ~ "Landscaping services",
      IND == 7780 ~ "Other administrative and other support services",
      IND == 7790 ~ "Waste management and remediation services",
      IND == 7860 ~ "Elementary and secondary schools",
      IND == 7870 ~ "Colleges and universities, including junior colleges",
      IND == 7880 ~ "Business, technical, and trade schools and training",
      IND == 7890 ~ "Other schools and instruction, and educational support services",
      IND == 7970 ~ "Offices of physicians",
      IND == 7980 ~ "Offices of dentists",
      IND == 7990 ~ "Offices of chiropractors",
      IND == 8070 ~ "Offices of optometrists",
      IND == 8080 ~ "Offices of other health practitioners",
      IND == 8090 ~ "Outpatient care centers",
      IND == 8170 ~ "Home health care services",
      IND == 8180 ~ "Other health care services",
      IND == 8191 ~ "General medical and surgical hospitals, and specialty (except psychiatric and substance abuse) hospitals",
      IND == 8192 ~ "Psychiatric and substance abuse hospitals",
      IND == 8270 ~ "Nursing care facilities (skilled nursing facilities)",
      IND == 8290 ~ "Residential care facilities, except skilled nursing facilities",
      IND == 8370 ~ "Individual and family services",
      IND == 8380 ~ "Community food and housing, and emergency services",
      IND == 8390 ~ "Vocational rehabilitation services",
      IND == 8470 ~ "Child day care services",
      IND == 8561 ~ "Performing arts companies",
      IND == 8562 ~ "Spectator sports",
      IND == 8563 ~ "Promoters of performing arts, sports, and similar events, agents and managers for artists, athletes, entertainers, and other public figures",
      IND == 8564 ~ "Independent artists, writers, and performers",
      IND == 8570 ~ "Museums, art galleries, historical sites, and similar institutions",
      IND == 8580 ~ "Bowling centers",
      IND == 8590 ~ "Other amusement, gambling, and recreation industries",
      IND == 8660 ~ "Traveler accommodation",
      IND == 8670 ~ "Recreational vehicle parks and camps, and rooming and boarding houses, dormitories, and workers' camps",
      IND == 8680 ~ "Restaurants and other food services",
      IND == 8690 ~ "Drinking places, alcoholic beverages",
      IND == 8770 ~ "Automotive repair and maintenance",
      IND == 8780 ~ "Car washes",
      IND == 8790 ~ "Electronic and precision equipment repair and maintenance",
      IND == 8870 ~ "Commercial and industrial machinery and equipment repair and maintenance",
      IND == 8891 ~ "Personal and household goods repair and maintenance",
      IND == 8970 ~ "Barber shops",
      IND == 8980 ~ "Beauty salons",
      IND == 8990 ~ "Nail salons and other personal care services",
      IND == 9070 ~ "Dry cleaning and laundry services",
      IND == 9080 ~ "Funeral homes, and cemeteries and crematories",
      IND == 9090 ~ "Other personal services",
      IND == 9160 ~ "Religious organizations",
      IND == 9170 ~ "Civic, social, advocacy organizations, and grantmaking and giving services",
      IND == 9180 ~ "Labor unions",
      IND == 9190 ~ "Business, professional, political, and similar organizations",
      IND == 9290 ~ "Private households",
      IND == 9370 ~ "Executive offices and legislative bodies",
      IND == 9380 ~ "Public finance activities",
      IND == 9390 ~ "Other general government and support",
      IND == 9470 ~ "Justice, public order, and safety activities",
      IND == 9480 ~ "Administration of human resource programs",
      IND == 9490 ~ "Administration of environmental quality and housing programs, urban planning and community development",
      IND == 9570 ~ "Administration of economic programs and space research",
      IND == 9590 ~ "National security and international affairs",
      IND == 9890 ~ "Armed Forces",
      TRUE ~ as.character(IND)
    )
  )


philly <- philly %>%
  mutate(
    occ_recoded = case_when(
      OCC == 0    ~ "Not in universe",
      OCC == 10   ~ "Chief executives",
      OCC == 20   ~ "General and operations managers",
      OCC == 40   ~ "Advertising and promotions managers",
      OCC == 51   ~ "Marketing managers",
      OCC == 52   ~ "Sales managers",
      OCC == 60   ~ "Public relations and fundraising managers",
      OCC == 101  ~ "Administrative services managers",
      OCC == 102  ~ "Facilities managers",
      OCC == 110  ~ "Computer and information systems managers",
      OCC == 120  ~ "Financial managers",
      OCC == 135  ~ "Compensation and benefits managers",
      OCC == 136  ~ "Human resources managers",
      OCC == 137  ~ "Training and development managers",
      OCC == 140  ~ "Industrial production managers",
      OCC == 150  ~ "Purchasing managers",
      OCC == 160  ~ "Transportation, storage, and distribution managers",
      OCC == 205  ~ "Farmers, ranchers, and other agricultural managers",
      OCC == 220  ~ "Construction managers",
      OCC == 230  ~ "Education and childcare administrators",
      OCC == 300  ~ "Architectural and engineering managers",
      OCC == 310  ~ "Food service managers",
      OCC == 335  ~ "Entertainment and recreation managers",
      OCC == 340  ~ "Lodging managers",
      OCC == 350  ~ "Medical and health services managers",
      OCC == 360  ~ "Natural sciences managers",
      OCC == 410  ~ "Property, real estate, and community association managers",
      OCC == 420  ~ "Social and community service managers",
      OCC == 425  ~ "Emergency management directors",
      OCC == 440  ~ "Managers, all other",
      OCC == 500  ~ "Agents and business managers of artists, performers, and athletes",
      OCC == 510  ~ "Buyers and purchasing agents, farm products",
      OCC == 520  ~ "Wholesale and retail buyers, except farm products",
      OCC == 530  ~ "Purchasing agents, except wholesale, retail, and farm products",
      OCC == 540  ~ "Claims adjusters, appraisers, examiners, and investigators",
      OCC == 565  ~ "Compliance officers",
      OCC == 600  ~ "Cost estimators",
      OCC == 630  ~ "Human resources workers",
      OCC == 640  ~ "Compensation, benefits, and job analysis specialists",
      OCC == 650  ~ "Training and development specialists",
      OCC == 700  ~ "Logisticians",
      OCC == 705  ~ "Project management specialists",
      OCC == 710  ~ "Management analysts",
      OCC == 725  ~ "Meeting, convention, and event planners",
      OCC == 726  ~ "Fundraisers",
      OCC == 735  ~ "Market research analysts and marketing specialists",
      OCC == 750  ~ "Business operations specialists, all other",
      OCC == 800  ~ "Accountants and auditors",
      OCC == 810  ~ "Property appraisers and assessors",
      OCC == 820  ~ "Budget analysts",
      OCC == 830  ~ "Credit analysts",
      OCC == 845  ~ "Financial and investment analysts",
      OCC == 850  ~ "Personal financial advisors",
      OCC == 860  ~ "Insurance underwriters",
      OCC == 900  ~ "Financial examiners",
      OCC == 910  ~ "Credit counselors and loan officers",
      OCC == 930  ~ "Tax examiners and collectors, and revenue agents",
      OCC == 940  ~ "Tax preparers",
      OCC == 960  ~ "Other financial specialists",
      OCC == 1005 ~ "Computer and information research scientists",
      OCC == 1006 ~ "Computer systems analysts",
      OCC == 1007 ~ "Information security analysts",
      OCC == 1010 ~ "Computer programmers",
      OCC == 1021 ~ "Software developers",
      OCC == 1022 ~ "Software quality assurance analysts and testers",
      OCC == 1031 ~ "Web developers",
      OCC == 1032 ~ "Web and digital interface designers",
      OCC == 1050 ~ "Computer support specialists",
      OCC == 1065 ~ "Database administrators and architects",
      OCC == 1105 ~ "Network and computer systems administrators",
      OCC == 1106 ~ "Computer network architects",
      OCC == 1108 ~ "Computer occupations, all other",
      OCC == 1200 ~ "Actuaries",
      OCC == 1220 ~ "Operations research analysts",
      OCC == 1240 ~ "Other mathematical science occupations",
      OCC == 1305 ~ "Architects, except landscape and naval",
      OCC == 1306 ~ "Landscape architects",
      OCC == 1310 ~ "Surveyors, cartographers, and photogrammetrists",
      OCC == 1320 ~ "Aerospace engineers",
      OCC == 1340 ~ "Bioengineers and biomedical engineers",
      OCC == 1350 ~ "Chemical engineers",
      OCC == 1360 ~ "Civil engineers",
      OCC == 1400 ~ "Computer hardware engineers",
      OCC == 1410 ~ "Electrical and electronics engineers",
      OCC == 1420 ~ "Environmental engineers",
      OCC == 1430 ~ "Industrial engineers, including health and safety",
      OCC == 1440 ~ "Marine engineers and naval architects",
      OCC == 1450 ~ "Materials engineers",
      OCC == 1460 ~ "Mechanical engineers",
      OCC == 1520 ~ "Petroleum engineers",
      OCC == 1530 ~ "Engineers, all other",
      OCC == 1541 ~ "Architectural and civil drafters",
      OCC == 1545 ~ "Other drafters",
      OCC == 1551 ~ "Electrical and electronic engineering technologists and technicians",
      OCC == 1555 ~ "Other engineering technologists and technicians, except drafters",
      OCC == 1560 ~ "Surveying and mapping technicians",
      OCC == 1600 ~ "Agricultural and food scientists",
      OCC == 1610 ~ "Biological scientists",
      OCC == 1640 ~ "Conservation scientists and foresters",
      OCC == 1650 ~ "Medical scientists",
      OCC == 1700 ~ "Astronomers and physicists",
      OCC == 1710 ~ "Atmospheric and space scientists",
      OCC == 1720 ~ "Chemists and materials scientists",
      OCC == 1745 ~ "Environmental scientists and specialists, including health",
      OCC == 1750 ~ "Geoscientists and hydrologists, except geographers",
      OCC == 1760 ~ "Physical scientists, all other",
      OCC == 1800 ~ "Economists",
      OCC == 1821 ~ "Clinical and counseling psychologists",
      OCC == 1822 ~ "School psychologists",
      OCC == 1825 ~ "Other psychologists",
      OCC == 1840 ~ "Urban and regional planners",
      OCC == 1860 ~ "Miscellaneous social scientists and related workers",
      OCC == 1900 ~ "Agricultural and food science technicians",
      OCC == 1910 ~ "Biological technicians",
      OCC == 1920 ~ "Chemical technicians",
      OCC == 1935 ~ "Environmental science and geoscience technicians",
      OCC == 1970 ~ "Other life, physical, and social science technicians",
      OCC == 1980 ~ "Occupational health and safety specialists and technicians",
      OCC == 2001 ~ "Substance abuse and behavioral disorder counselors",
      OCC == 2002 ~ "Educational, guidance, and career counselors and advisors",
      OCC == 2003 ~ "Marriage and family therapists",
      OCC == 2004 ~ "Mental health counselors",
      OCC == 2005 ~ "Rehabilitation counselors",
      OCC == 2006 ~ "Counselors, all other",
      OCC == 2011 ~ "Child, family, and school social workers",
      OCC == 2012 ~ "Healthcare social workers",
      OCC == 2013 ~ "Mental health and substance abuse social workers",
      OCC == 2014 ~ "Social workers, all other",
      OCC == 2015 ~ "Probation officers and correctional treatment specialists",
      OCC == 2016 ~ "Social and human service assistants",
      OCC == 2025 ~ "Other community and social service specialists",
      OCC == 2040 ~ "Clergy",
      OCC == 2050 ~ "Directors, religious activities and education",
      OCC == 2060 ~ "Religious workers, all other",
      OCC == 2100 ~ "Lawyers",
      OCC == 2105 ~ "Judicial law clerks",
      OCC == 2145 ~ "Paralegals and legal assistants",
      OCC == 2170 ~ "Title examiners, abstractors, and searchers",
      OCC == 2180 ~ "Legal support workers, all other",
      OCC == 2205 ~ "Postsecondary teachers",
      OCC == 2300 ~ "Preschool and kindergarten teachers",
      OCC == 2310 ~ "Elementary and middle school teachers",
      OCC == 2320 ~ "Secondary school teachers",
      OCC == 2330 ~ "Special education teachers",
      OCC == 2350 ~ "Tutors",
      OCC == 2360 ~ "Other teachers and instructors",
      OCC == 2400 ~ "Archivists, curators, and museum technicians",
      OCC == 2435 ~ "Librarians and media collections specialists",
      OCC == 2440 ~ "Library technicians",
      OCC == 2545 ~ "Teaching assistants",
      OCC == 2555 ~ "Other educational instruction and library workers",
      OCC == 2600 ~ "Artists and related workers",
      OCC == 2631 ~ "Commercial and industrial designers",
      OCC == 2632 ~ "Fashion designers",
      OCC == 2633 ~ "Floral designers",
      OCC == 2634 ~ "Graphic designers",
      OCC == 2635 ~ "Interior designers",
      OCC == 2636 ~ "Merchandise displayers and window trimmers",
      OCC == 2640 ~ "Other designers",
      OCC == 2700 ~ "Actors",
      OCC == 2710 ~ "Producers and directors",
      OCC == 2721 ~ "Athletes and sports competitors",
      OCC == 2722 ~ "Coaches and scouts",
      OCC == 2723 ~ "Umpires, referees, and other sports officials",
      OCC == 2740 ~ "Dancers and choreographers",
      OCC == 2751 ~ "Music directors and composers",
      OCC == 2752 ~ "Musicians and singers",
      OCC == 2755 ~ "Disc jockeys, except radio",
      OCC == 2770 ~ "Entertainers and performers, sports and related workers, all other",
      OCC == 2805 ~ "Broadcast announcers and radio disc jockeys",
      OCC == 2810 ~ "News analysts, reporters, and journalists",
      OCC == 2825 ~ "Public relations specialists",
      OCC == 2830 ~ "Editors",
      OCC == 2840 ~ "Technical writers",
      OCC == 2850 ~ "Writers and authors",
      OCC == 2861 ~ "Interpreters and translators",
      OCC == 2862 ~ "Court reporters and simultaneous captioners",
      OCC == 2865 ~ "Media and communication workers, all other",
      OCC == 2905 ~ "Broadcast, sound, and lighting technicians",
      OCC == 2910 ~ "Photographers",
      OCC == 2920 ~ "Television, video, and film camera operators and editors",
      OCC == 3000 ~ "Chiropractors",
      OCC == 3010 ~ "Dentists",
      OCC == 3030 ~ "Dietitians and nutritionists",
      OCC == 3040 ~ "Optometrists",
      OCC == 3050 ~ "Pharmacists",
      OCC == 3090 ~ "Other physicians",
      OCC == 3100 ~ "Surgeons",
      OCC == 3110 ~ "Physician assistants",
      OCC == 3120 ~ "Podiatrists",
      OCC == 3140 ~ "Audiologists",
      OCC == 3150 ~ "Occupational therapists",
      OCC == 3160 ~ "Physical therapists",
      OCC == 3200 ~ "Radiation therapists",
      OCC == 3210 ~ "Recreational therapists",
      OCC == 3220 ~ "Respiratory therapists",
      OCC == 3230 ~ "Speech-language pathologists",
      OCC == 3245 ~ "Therapists, all other",
      OCC == 3250 ~ "Veterinarians",
      OCC == 3255 ~ "Registered nurses",
      OCC == 3256 ~ "Nurse anesthetists",
      OCC == 3258 ~ "Nurse practitioners",
      OCC == 3261 ~ "Acupuncturists",
      OCC == 3270 ~ "Healthcare diagnosing or treating practitioners, all other",
      OCC == 3300 ~ "Clinical laboratory technologists and technicians",
      OCC == 3310 ~ "Dental hygienists",
      OCC == 3321 ~ "Cardiovascular technologists and technicians",
      OCC == 3322 ~ "Diagnostic medical sonographers",
      OCC == 3323 ~ "Radiologic technologists and technicians",
      OCC == 3324 ~ "Magnetic resonance imaging technologists",
      OCC == 3330 ~ "Nuclear medicine technologists and medical dosimetrists",
      OCC == 3401 ~ "Emergency medical technicians",
      OCC == 3402 ~ "Paramedics",
      OCC == 3421 ~ "Pharmacy technicians",
      OCC == 3422 ~ "Psychiatric technicians",
      OCC == 3423 ~ "Surgical technologists",
      OCC == 3424 ~ "Veterinary technologists and technicians",
      OCC == 3430 ~ "Dietetic technicians and ophthalmic medical technicians",
      OCC == 3500 ~ "Licensed practical and licensed vocational nurses",
      OCC == 3515 ~ "Medical records specialists",
      OCC == 3520 ~ "Opticians, dispensing",
      OCC == 3545 ~ "Miscellaneous health technologists and technicians",
      OCC == 3550 ~ "Other healthcare practitioners and technical occupations",
      OCC == 3601 ~ "Home health aides",
      OCC == 3602 ~ "Personal care aides",
      OCC == 3603 ~ "Nursing assistants",
      OCC == 3605 ~ "Orderlies and psychiatric aides",
      OCC == 3610 ~ "Occupational therapy assistants and aides",
      OCC == 3620 ~ "Physical therapist assistants and aides",
      OCC == 3630 ~ "Massage therapists",
      OCC == 3640 ~ "Dental assistants",
      OCC == 3645 ~ "Medical assistants",
      OCC == 3646 ~ "Medical transcriptionists",
      OCC == 3647 ~ "Pharmacy aides",
      OCC == 3648 ~ "Veterinary assistants and laboratory animal caretakers",
      OCC == 3649 ~ "Phlebotomists",
      OCC == 3655 ~ "Other healthcare support workers",
      OCC == 3700 ~ "First-line supervisors of correctional officers",
      OCC == 3710 ~ "First-line supervisors of police and detectives",
      OCC == 3720 ~ "First-line supervisors of firefighting and prevention workers",
      OCC == 3725 ~ "First-line supervisors of security workers",
      OCC == 3740 ~ "Firefighters",
      OCC == 3750 ~ "Fire inspectors",
      OCC == 3801 ~ "Bailiffs",
      OCC == 3802 ~ "Correctional officers and jailers",
      OCC == 3820 ~ "Detectives and criminal investigators",
      OCC == 3840 ~ "Parking enforcement workers",
      OCC == 3870 ~ "Police officers",
      OCC == 3900 ~ "Animal control workers",
      OCC == 3910 ~ "Private detectives and investigators",
      OCC == 3930 ~ "Security guards and gambling surveillance officers",
      OCC == 3940 ~ "Crossing guards and flaggers",
      OCC == 3945 ~ "Transportation security screeners",
      OCC == 3946 ~ "School bus monitors",
      OCC == 3960 ~ "Other protective service workers",
      OCC == 4000 ~ "Chefs and head cooks",
      OCC == 4010 ~ "First-line supervisors of food preparation and serving workers",
      OCC == 4020 ~ "Cooks",
      OCC == 4030 ~ "Food preparation workers",
      OCC == 4040 ~ "Bartenders",
      OCC == 4055 ~ "Fast food and counter workers",
      OCC == 4110 ~ "Waiters and waitresses",
      OCC == 4120 ~ "Food servers, nonrestaurant",
      OCC == 4130 ~ "Dining room and cafeteria attendants and bartender helpers",
      OCC == 4140 ~ "Dishwashers",
      OCC == 4150 ~ "Hosts and hostesses, restaurant, lounge, and coffee shop",
      OCC == 4160 ~ "Food preparation and serving related workers, all other",
      OCC == 4200 ~ "First-line supervisors of housekeeping and janitorial workers",
      OCC == 4210 ~ "First-line supervisors of landscaping, lawn service, and groundskeeping workers",
      OCC == 4220 ~ "Janitors and building cleaners",
      OCC == 4230 ~ "Maids and housekeeping cleaners",
      OCC == 4240 ~ "Pest control workers",
      OCC == 4251 ~ "Landscaping and groundskeeping workers",
      OCC == 4252 ~ "Tree trimmers and pruners",
      OCC == 4255 ~ "Other grounds maintenance workers",
      OCC == 4330 ~ "Supervisors of personal care and service workers",
      OCC == 4340 ~ "Animal trainers",
      OCC == 4350 ~ "Animal caretakers",
      OCC == 4400 ~ "Gambling services workers",
      OCC == 4420 ~ "Ushers, lobby attendants, and ticket takers",
      OCC == 4435 ~ "Other entertainment attendants and related workers",
      OCC == 4461 ~ "Embalmers, crematory operators and funeral attendants",
      OCC == 4465 ~ "Morticians, undertakers, and funeral arrangers",
      OCC == 4500 ~ "Barbers",
      OCC == 4510 ~ "Hairdressers, hairstylists, and cosmetologists",
      OCC == 4521 ~ "Manicurists and pedicurists",
      OCC == 4522 ~ "Skincare specialists",
      OCC == 4525 ~ "Other personal appearance workers",
      OCC == 4530 ~ "Baggage porters, bellhops, and concierges",
      OCC == 4540 ~ "Tour and travel guides",
      OCC == 4600 ~ "Childcare workers",
      OCC == 4621 ~ "Exercise trainers and group fitness instructors",
      OCC == 4622 ~ "Recreation workers",
      OCC == 4640 ~ "Residential advisors",
      OCC == 4655 ~ "Personal care and service workers, all other",
      OCC == 4700 ~ "First-Line supervisors of retail sales workers",
      OCC == 4710 ~ "First-Line supervisors of non-retail sales workers",
      OCC == 4720 ~ "Cashiers",
      OCC == 4740 ~ "Counter and rental clerks",
      OCC == 4750 ~ "Parts salespersons",
      OCC == 4760 ~ "Retail salespersons",
      OCC == 4800 ~ "Advertising sales agents",
      OCC == 4810 ~ "Insurance sales agents",
      OCC == 4820 ~ "Securities, commodities, and financial services sales agents",
      OCC == 4830 ~ "Travel agents",
      OCC == 4840 ~ "Sales representatives of services, except advertising, insurance, financial services, and travel",
      OCC == 4850 ~ "Sales representatives, wholesale and manufacturing",
      OCC == 4900 ~ "Models, demonstrators, and product promoters",
      OCC == 4920 ~ "Real estate brokers and sales agents",
      OCC == 4930 ~ "Sales engineers",
      OCC == 4940 ~ "Telemarketers",
      OCC == 4950 ~ "Door-to-door sales workers, news and street vendors, and related workers",
      OCC == 4965 ~ "Sales and related workers, all other",
      OCC == 5000 ~ "First-Line supervisors of office and administrative support workers",
      OCC == 5010 ~ "Switchboard operators, including answering service",
      OCC == 5020 ~ "Telephone operators",
      OCC == 5040 ~ "Communications equipment operators, all other",
      OCC == 5100 ~ "Bill and account collectors",
      OCC == 5110 ~ "Billing and posting clerks",
      OCC == 5120 ~ "Bookkeeping, accounting, and auditing clerks",
      OCC == 5140 ~ "Payroll and timekeeping clerks",
      OCC == 5150 ~ "Procurement clerks",
      OCC == 5160 ~ "Tellers",
      OCC == 5165 ~ "Financial clerks, all other",
      OCC == 5220 ~ "Court, municipal, and license clerks",
      OCC == 5230 ~ "Credit authorizers, checkers, and clerks",
      OCC == 5240 ~ "Customer service representatives",
      OCC == 5250 ~ "Eligibility interviewers, government programs",
      OCC == 5260 ~ "File clerks",
      OCC == 5300 ~ "Hotel, motel, and resort desk clerks",
      OCC == 5310 ~ "Interviewers, except eligibility and loan",
      OCC == 5320 ~ "Library assistants, clerical",
      OCC == 5330 ~ "Loan interviewers and clerks",
      OCC == 5340 ~ "New accounts clerks",
      OCC == 5350 ~ "Order clerks",
      OCC == 5360 ~ "Human resources assistants, except payroll and timekeeping",
      OCC == 5400 ~ "Receptionists and information clerks",
      OCC == 5410 ~ "Reservation and transportation ticket agents and travel clerks",
      OCC == 5420 ~ "Information and record clerks, all other",
      OCC == 5500 ~ "Cargo and freight agents",
      OCC == 5510 ~ "Couriers and messengers",
      OCC == 5521 ~ "Public safety telecommunicators",
      OCC == 5522 ~ "Dispatchers, except police, fire, and ambulance",
      OCC == 5530 ~ "Meter readers, utilities",
      OCC == 5540 ~ "Postal service clerks",
      OCC == 5550 ~ "Postal service mail carriers",
      OCC == 5560 ~ "Postal service mail sorters, processors, and processing machine operators",
      OCC == 5600 ~ "Production, planning, and expediting clerks",
      OCC == 5610 ~ "Shipping, receiving, and inventory clerks",
      OCC == 5630 ~ "Weighers, measurers, checkers, and samplers, recordkeeping",
      OCC == 5710 ~ "Executive secretaries and executive administrative assistants",
      OCC == 5720 ~ "Legal secretaries and administrative assistants",
      OCC == 5730 ~ "Medical secretaries and administrative assistants",
      OCC == 5740 ~ "Secretaries and administrative assistants, except legal, medical, and executive",
      OCC == 5810 ~ "Data entry keyers",
      OCC == 5820 ~ "Word processors and typists",
      OCC == 5840 ~ "Insurance claims and policy processing clerks",
      OCC == 5850 ~ "Mail clerks and mail machine operators, except postal service",
      OCC == 5860 ~ "Office clerks, general",
      OCC == 5900 ~ "Office machine operators, except computer",
      OCC == 5910 ~ "Proofreaders and copy markers",
      OCC == 5920 ~ "Statistical assistants",
      OCC == 5940 ~ "Office and administrative support workers, all other",
      OCC == 6005 ~ "First-line supervisors of farming, fishing, and forestry workers",
      OCC == 6010 ~ "Agricultural inspectors",
      OCC == 6040 ~ "Graders and sorters, agricultural products",
      OCC == 6050 ~ "Miscellaneous agricultural workers",
      OCC == 6115 ~ "Fishing and hunting workers",
      OCC == 6120 ~ "Forest and conservation workers",
      OCC == 6130 ~ "Logging workers",
      OCC == 6200 ~ "First-line supervisors of construction trades and extraction workers",
      OCC == 6210 ~ "Boilermakers",
      OCC == 6220 ~ "Brickmasons, blockmasons, and stonemasons",
      OCC == 6230 ~ "Carpenters",
      OCC == 6240 ~ "Carpet, floor, and tile installers and finishers",
      OCC == 6250 ~ "Cement masons, concrete finishers, and terrazzo workers",
      OCC == 6260 ~ "Construction laborers",
      OCC == 6305 ~ "Construction equipment operators",
      OCC == 6330 ~ "Drywall installers, ceiling tile installers, and tapers",
      OCC == 6355 ~ "Electricians",
      OCC == 6360 ~ "Glaziers",
      OCC == 6400 ~ "Insulation workers",
      OCC == 6410 ~ "Painters and paperhangers",
      OCC == 6441 ~ "Pipelayers",
      OCC == 6442 ~ "Plumbers, pipefitters, and steamfitters",
      OCC == 6460 ~ "Plasterers and stucco masons",
      OCC == 6515 ~ "Roofers",
      OCC == 6520 ~ "Sheet metal workers",
      OCC == 6530 ~ "Structural iron and steel workers",
      OCC == 6540 ~ "Solar photovoltaic installers",
      OCC == 6600 ~ "Helpers, construction trades",
      OCC == 6660 ~ "Construction and building inspectors",
      OCC == 6700 ~ "Elevator and escalator installers and repairers",
      OCC == 6710 ~ "Fence erectors",
      OCC == 6720 ~ "Hazardous materials removal workers",
      OCC == 6730 ~ "Highway maintenance workers",
      OCC == 6740 ~ "Rail-track laying and maintenance equipment operators",
      OCC == 6765 ~ "Miscellaneous construction and related workers",
      OCC == 6800 ~ "Derrick, rotary drill, and service unit operators, oil and gas",
      OCC == 6825 ~ "Earth drillers, except oil and gas",
      OCC == 6835 ~ "Explosives workers, ordnance handling experts, and blasters",
      OCC == 6850 ~ "Underground mining machine operators",
      OCC == 6950 ~ "Other extraction workers",
      OCC == 7000 ~ "First-line supervisors of mechanics, installers, and repairers",
      OCC == 7010 ~ "Computer, automated teller, and office machine repairers",
      OCC == 7020 ~ "Radio and telecommunications equipment installers and repairers",
      OCC == 7030 ~ "Avionics technicians",
      OCC == 7040 ~ "Electric motor, power tool, and related repairers",
      OCC == 7100 ~ "Electrical and electronics repairers, industrial and utility",
      OCC == 7120 ~ "Audiovisual equipment installers and repairers",
      OCC == 7130 ~ "Security and fire alarm systems installers",
      OCC == 7140 ~ "Aircraft mechanics and service technicians",
      OCC == 7150 ~ "Automotive body and related repairers",
      OCC == 7160 ~ "Automotive glass installers and repairers",
      OCC == 7200 ~ "Automotive service technicians and mechanics",
      OCC == 7210 ~ "Bus and truck mechanics and diesel engine specialists",
      OCC == 7220 ~ "Heavy vehicle and mobile equipment service technicians and mechanics",
      OCC == 7240 ~ "Small engine mechanics",
      OCC == 7260 ~ "Miscellaneous vehicle and mobile equipment mechanics, installers, and repairers",
      OCC == 7300 ~ "Control and valve installers and repairers",
      OCC == 7315 ~ "Heating, air conditioning, and refrigeration mechanics and installers",
      OCC == 7320 ~ "Home appliance repairers",
      OCC == 7330 ~ "Industrial and refractory machinery mechanics",
      OCC == 7340 ~ "Maintenance and repair workers, general",
      OCC == 7350 ~ "Maintenance workers, machinery",
      OCC == 7360 ~ "Millwrights",
      OCC == 7410 ~ "Electrical power-line installers and repairers",
      OCC == 7420 ~ "Telecommunications line installers and repairers",
      OCC == 7430 ~ "Precision instrument and equipment repairers",
      OCC == 7510 ~ "Coin, vending, and amusement machine servicers and repairers",
      OCC == 7540 ~ "Locksmiths and safe repairers",
      OCC == 7560 ~ "Riggers",
      OCC == 7610 ~ "Helpers--installation, maintenance, and repair workers",
      OCC == 7640 ~ "Other installation, maintenance, and repair workers",
      OCC == 7700 ~ "First-line supervisors of production and operating workers",
      OCC == 7720 ~ "Electrical, electronics, and electromechanical assemblers",
      OCC == 7730 ~ "Engine and other machine assemblers",
      OCC == 7740 ~ "Structural metal fabricators and fitters",
      OCC == 7750 ~ "Other assemblers and fabricators",
      OCC == 7800 ~ "Bakers",
      OCC == 7810 ~ "Butchers and other meat, poultry, and fish processing workers",
      OCC == 7830 ~ "Food and tobacco roasting, baking, and drying machine operators and tenders",
      OCC == 7840 ~ "Food batchmakers",
      OCC == 7850 ~ "Food cooking machine operators and tenders",
      OCC == 7855 ~ "Food processing workers, all other",
      OCC == 7905 ~ "Computer numerically controlled tool operators and programmers",
      OCC == 7925 ~ "Forming machine setters, operators, and tenders, metal and plastic",
      OCC == 7950 ~ "Cutting, punching, and press machine setters, operators, and tenders, metal and plastic",
      OCC == 8000 ~ "Grinding, lapping, polishing, and buffing machine tool setters, operators, and tenders, metal and plastic",
      OCC == 8025 ~ "Other machine tool setters, operators, and tenders, metal and plastic",
      OCC == 8030 ~ "Machinists",
      OCC == 8040 ~ "Metal furnace operators, tenders, pourers, and casters",
      OCC == 8100 ~ "Molders and molding machine setters, operators, and tenders, metal and plastic",
      OCC == 8130 ~ "Tool and die makers",
      OCC == 8140 ~ "Welding, soldering, and brazing workers",
      OCC == 8225 ~ "Other metal workers and plastic workers",
      OCC == 8250 ~ "Prepress technicians and workers",
      OCC == 8255 ~ "Printing press operators",
      OCC == 8256 ~ "Print binding and finishing workers",
      OCC == 8300 ~ "Laundry and dry-cleaning workers",
      OCC == 8310 ~ "Pressers, textile, garment, and related materials",
      OCC == 8320 ~ "Sewing machine operators",
      OCC == 8335 ~ "Shoe and leather workers",
      OCC == 8350 ~ "Tailors, dressmakers, and sewers",
      OCC == 8365 ~ "Textile machine setters, operators, and tenders",
      OCC == 8450 ~ "Upholsterers",
      OCC == 8465 ~ "Other textile, apparel, and furnishings workers",
      OCC == 8500 ~ "Cabinetmakers and bench carpenters",
      OCC == 8510 ~ "Furniture finishers",
      OCC == 8530 ~ "Sawing machine setters, operators, and tenders, wood",
      OCC == 8540 ~ "Woodworking machine setters, operators, and tenders, except sawing",
      OCC == 8555 ~ "Other woodworkers",
      OCC == 8600 ~ "Power plant operators, distributors, and dispatchers",
      OCC == 8610 ~ "Stationary engineers and boiler operators",
      OCC == 8620 ~ "Water and wastewater treatment plant and system operators",
      OCC == 8630 ~ "Miscellaneous plant and system operators",
      OCC == 8640 ~ "Chemical processing machine setters, operators, and tenders",
      OCC == 8650 ~ "Crushing, grinding, polishing, mixing, and blending workers",
      OCC == 8710 ~ "Cutting workers",
      OCC == 8720 ~ "Extruding, forming, pressing, and compacting machine setters, operators, and tenders",
      OCC == 8730 ~ "Furnace, kiln, oven, drier, and kettle operators and tenders",
      OCC == 8740 ~ "Inspectors, testers, sorters, samplers, and weighers",
      OCC == 8750 ~ "Jewelers and precious stone and metal workers",
      OCC == 8760 ~ "Dental and ophthalmic laboratory technicians and medical appliance technicians",
      OCC == 8800 ~ "Packaging and filling machine operators and tenders",
      OCC == 8810 ~ "Painting workers",
      OCC == 8830 ~ "Photographic process workers and processing machine operators",
      OCC == 8850 ~ "Adhesive bonding machine operators and tenders",
      OCC == 8910 ~ "Etchers and engravers",
      OCC == 8920 ~ "Molders, shapers, and casters, except metal and plastic",
      OCC == 8930 ~ "Paper goods machine setters, operators, and tenders",
      OCC == 8940 ~ "Tire builders",
      OCC == 8950 ~ "Helpers--production workers",
      OCC == 8990 ~ "Other production workers",
      OCC == 9005 ~ "Supervisors of transportation and material moving workers",
      OCC == 9030 ~ "Aircraft pilots and flight engineers",
      OCC == 9040 ~ "Air traffic controllers and airfield operations specialists",
      OCC == 9050 ~ "Flight attendants",
      OCC == 9110 ~ "Ambulance drivers and attendants, except emergency medical technicians",
      OCC == 9121 ~ "Bus drivers, school",
      OCC == 9122 ~ "Bus drivers, transit and intercity",
      OCC == 9130 ~ "Driver/sales workers and truck drivers",
      OCC == 9141 ~ "Shuttle drivers and chauffeurs",
      OCC == 9142 ~ "Taxi drivers",
      OCC == 9150 ~ "Motor vehicle operators, all other",
      OCC == 9210 ~ "Locomotive engineers and operators",
      OCC == 9240 ~ "Railroad conductors and yardmasters",
      OCC == 9265 ~ "Other rail transportation workers",
      OCC == 9300 ~ "Sailors and marine oilers",
      OCC == 9310 ~ "Ship and boat captains and operators",
      OCC == 9350 ~ "Parking attendants",
      OCC == 9365 ~ "Transportation service attendants",
      OCC == 9410 ~ "Transportation inspectors",
      OCC == 9415 ~ "Passenger attendants",
      OCC == 9430 ~ "Other transportation workers",
      OCC == 9510 ~ "Crane and tower operators",
      OCC == 9570 ~ "Conveyor, dredge, and hoist and winch operators",
      OCC == 9600 ~ "Industrial truck and tractor operators",
      OCC == 9610 ~ "Cleaners of vehicles and equipment",
      OCC == 9620 ~ "Laborers and freight, stock, and material movers, hand",
      OCC == 9630 ~ "Machine feeders and offbearers",
      OCC == 9640 ~ "Packers and packagers, hand",
      OCC == 9645 ~ "Stockers and order fillers",
      OCC == 9650 ~ "Pumping station operators",
      OCC == 9720 ~ "Refuse and recyclable material collectors",
      OCC == 9760 ~ "Other material moving workers",
      OCC == 9840 ~ "Armed Forces",
      TRUE ~ as.character(OCC)
    )
  )

philly <- philly %>%
  mutate(
    industry_label = case_when(
      IND == 0 ~ "Not applicable",
      IND >= 170 & IND <= 290 ~ "Agriculture, Forestry, Fishing and Hunting",
      IND >= 370 & IND <= 490 ~ "Mining, Quarrying, and Oil and Gas Extraction",
      IND == 770 ~ "Construction",
      IND >= 1070 & IND <= 3990 ~ "Manufacturing",
      IND >= 4070 & IND <= 4590 ~ "Wholesale Trade",
      IND >= 4670 & IND <= 5791 ~ "Retail Trade",
      IND %in% c(570, 580, 590, 670, 680, 690) ~ "Utilities",
      IND >= 6070 & IND <= 6390 ~ "Transportation and Warehousing",
      IND >= 6471 & IND <= 6781 ~ "Information",
      IND >= 6871 & IND <= 6992 ~ "Finance and Insurance",
      IND >= 7071 & IND <= 7190 ~ "Real Estate and Rental and Leasing",
      IND >= 7270 & IND <= 7490 ~ "Professional, Scientific, and Technical Services",
      IND == 7570 ~ "Management of Companies and Enterprises",
      IND >= 7580 & IND <= 7790 ~ "Administrative and Support and Waste Management Services",
      IND >= 7860 & IND <= 7890 ~ "Educational Services",
      IND >= 7970 & IND <= 8470 ~ "Health Care and Social Assistance",
      IND >= 8561 & IND <= 8690 ~ "Arts, Entertainment, and Recreation / Accommodation and Food Services",
      IND >= 8770 & IND <= 9290 ~ "Other Services, Except Public Administration",
      IND >= 9370 & IND <= 9590 ~ "Public Administration",
      IND >= 9670 & IND <= 9870 ~ "Military",
      IND == 9920 ~ "Unemployed or Not in Universe",
      TRUE ~ as.character(IND)
    ),
    naics_code = case_when(
      IND == 0 ~ NA_character_,
      IND >= 170 & IND <= 290 ~ "11",
      IND >= 370 & IND <= 490 ~ "21",
      IND == 770 ~ "23",
      IND >= 1070 & IND <= 3990 ~ "31-33",
      IND >= 4070 & IND <= 4590 ~ "42",
      IND >= 4670 & IND <= 5791 ~ "44-45",
      IND %in% c(570,580,590,670,680,690) ~ "22",
      IND >= 6070 & IND <= 6390 ~ "48-49",
      IND >= 6471 & IND <= 6781 ~ "51",
      IND >= 6871 & IND <= 6992 ~ "52",
      IND >= 7071 & IND <= 7190 ~ "53",
      IND >= 7270 & IND <= 7490 ~ "54",
      IND == 7570 ~ "55",
      IND >= 7580 & IND <= 7790 ~ "56",
      IND >= 7860 & IND <= 7890 ~ "61",
      IND >= 7970 & IND <= 8470 ~ "62",
      IND >= 8561 & IND <= 8690 ~ "71-72",
      IND >= 8770 & IND <= 9290 ~ "81",
      IND >= 9370 & IND <= 9590 ~ "92",
      IND >= 9670 & IND <= 9870 ~ "Military",
      IND == 9920 ~ NA_character_,
      TRUE ~ NA_character_
    )
  )


glimpse(philly)

philly <- philly %>%
  mutate(date = make_date(YEAR, MONTH, 1))
industry_summary <- philly %>%
  filter(empstat_recoded == "At work") %>%
  group_by(industry_label, date) %>%
  summarise(employment = n(), .groups = "drop")

relevant_dates <- c(make_date(2025, 1, 1), make_date(2024, 12, 1), make_date(2024, 1, 1))
industry_summary_filtered <- industry_summary %>%
  filter(date %in% relevant_dates)



jan2025 <- industry_summary_filtered %>% filter(date == make_date(2025, 1, 1))
dec2024 <- industry_summary_filtered %>% filter(date == make_date(2024, 12, 1))
jan2024 <- industry_summary_filtered %>% filter(date == make_date(2024, 1, 1))

industry_changes <- jan2025 %>%
  left_join(dec2024, by = "industry_label", suffix = c("_jan2025", "_dec2024")) %>%
  left_join(jan2024, by = "industry_label") %>%
  rename(employment_jan2024 = employment,
         date_jan2024 = date)
industry_changes <- industry_changes %>%
  mutate(
    monthly_change = (employment_jan2025 - employment_dec2024) / employment_dec2024 * 100,
    yearly_change  = (employment_jan2025 - employment_jan2024) / employment_jan2024 * 100
  )

print(industry_changes)
